### ISSUE TITLE
Normalize topic name

### ISSUE THREAD

**Issue by gaetancollaud** [gaetancollaud/digitalstrom-mqtt#1]
Option to "normalize" the topic name.
- keep all letters and numbers
- replace spaces with `_`
- replace '/' with '_'
- remove special char

**Comment by dylancollaud** [comment]
Add Environnement variable to change Topic name by the ID of the device

**Comment by gaetancollaud** [comment]
> Add Environnement variable to change Topic name by the ID of the device

created #5 because it's not related to the normalization of the special chars.
