### ISSUE TITLE
Roller Shutter Angle influences position

### ISSUE THREAD

**Issue by Sapp00** [gaetancollaud/digitalstrom-mqtt#10]
Hi,

if I set the shadeOpeningAngleOutside to 0, it works roughly. shadePositionOutside=100->opened, 0->closed; but for example 50 isn't half opened, but thats not a real problem in my case.

The main issue is that if I set the shadeOpeningAngleOutside to a value larger than 0, it doesn't fully open/close anymore. If I set shadeOpeningAngleOutside to 100 for example and shadePositionOutside to 100 (it should be fully opened), it is just like 60% opened.

**Comment by gaetancollaud** [comment]
Hello,

This is unfortunately how digitalSTROM (and others work). They use the time to switch the position and angle. It's not really accurate. They don't have an encoder on the motor.

Results are worst if the calibration is bad. I would suggest trying to calibrate again to see if you have a better result, but I doubt it.
