### ISSUE TITLE
Installation with Docker Compose

### ISSUE THREAD

**Issue by djacid** [gaetancollaud/digitalstrom-mqtt#15]
Could you please tell me how I could install it with docker compose? Thank you in advance

**Comment by gaetancollaud** [comment]
Just use the provided docker-compose file: https://github.com/gaetancollaud/digitalstrom-mqtt/blob/master/docker-compose.yml

**Comment by djacid** [comment]
I have already done this but I got this error:
“ERROR: Cannot locate specified Dockerfile: Dockerfile”

**Comment by gaetancollaud** [comment]
Just remove the line 5: https://github.com/gaetancollaud/digitalstrom-mqtt/blob/master/docker-compose.yml#L5

And you maybe want to create a `.env` file with your config. Ex:

```
DIGITALSTROM_HOST=192.168.10.50
DIGITALSTROM_USERNAME=dssadmin
DIGITALSTROM_PASSWORD=your-password
MQTT_URL=tcp://192.168.10.12:1883
REFRESH_AT_START=true
```

**Comment by djacid** [comment]
Now there is another error. 
ERROR: manifest for gaetancollaud/digitalstrom-mqtt:dev not found: manifest unknown: manifest unknown

**Comment by gaetancollaud** [comment]
change `dev` for `latest`

**Comment by djacid** [comment]
Thank you, that's worked, but unfortunately I can't see any device on mqtt explorer

**Comment by djacid** [comment]
Perfetct, after some tries now I can see my devices. Thank you very much.

**Comment by gaetancollaud** [comment]
No problem, I will note to myself to have a better example with docker compose.
