### ISSUE TITLE
Cannot setup sensor for total Consumptipn

### ISSUE THREAD

**Issue by djacid** [gaetancollaud/digitalstrom-mqtt#18]
<img width="240" alt="Screenshot 2021-08-07 at 11 37 06 PM" src="https://user-images.githubusercontent.com/13071634/128613311-aa1e535d-8f46-43dc-a1ae-98d9304fcdec.png">
Hello, as you can see for some reason consumption is not working, and returns only the number 1. Secondly, there is no "chambres" word in the tree.

**Comment by gaetancollaud** [comment]
Hello,

This software uses the property tree to get those values, can you show me what's in there for you ? It's in the system tab.

Example:
![Screenshot from 2021-08-09 09-51-57](https://user-images.githubusercontent.com/3659220/128674824-2db5e4d4-2ea9-4789-a29f-ca19bbd81b53.png)

The name should be defined. And normally the `consumptionW` in MQTT should matches the `powerConsumption` of the tree.

**Comment by djacid** [comment]
<img width="570" alt="Screenshot 2021-08-10 at 12 16 16 AM" src="https://user-images.githubusercontent.com/13071634/128775600-3ea6ccb5-c4b1-4e5c-b06e-f0d17fd67a31.png">
<img width="440" alt="Screenshot 2021-08-10 at 12 16 47 AM" src="https://user-images.githubusercontent.com/13071634/128775655-da5a9c3f-a001-4d27-854d-dd67069cd3ac.png">
<img width="713" alt="Screenshot 2021-08-10 at 12 17 15 AM" src="https://user-images.githubusercontent.com/13071634/128775703-c99c3ad1-4be3-4697-b2dc-17b3d778bbf1.png">
<img width="597" alt="Screenshot 2021-08-10 at 12 17 44 AM" src="https://user-images.githubusercontent.com/13071634/128775756-b59c89cc-0006-40cd-8536-8a6616064888.png">
<img width="587" alt="Screenshot 2021-08-10 at 12 18 37 AM" src="https://user-images.githubusercontent.com/13071634/128775878-fd8aaff2-1a60-4db3-be04-3c358656f2ee.png">
<img width="469" alt="Screenshot 2021-08-10 at 12 19 12 AM" src="https://user-images.githubusercontent.com/13071634/128775935-5d592c96-add8-476f-8d4b-943041609d2e.png">

**Comment by djacid** [comment]
I don't know what this devis is. I think is there by mistake and I don't know how I could delete this. I have installed your component via docker-compose and it seems that docker-compose cannot see that there is a new version of your component.

**Comment by djacid** [comment]
Ok I found a reason to update the image of docker. Now it seems that the issue has fixed.
<img width="353" alt="Screenshot 2021-08-11 at 8 29 13 PM" src="https://user-images.githubusercontent.com/13071634/129075637-ab8220fa-1108-447a-b534-0b13015a6370.png">
Thank you for this update!

**Comment by djacid** [comment]
After this update, I noticed an issue. Now, if I push the wall switch-button, mqtt does not update the status of the light. For example, if I turn on the lights manually with the wall switch, mqtt does not update the status of this light as turned on

**Comment by djacid** [comment]
By downgrading back to 1.4.1 version, this bug seems to be fixed. There is also something stange. After downgrading, dsmeters are still appearing correctly. I think database has stored the meters from the latest version and keep them after downgrading. Now, everything is working as it should.

**Comment by gaetancollaud** [comment]
The only change was a test to remove the unnamed circuit. I don't think downgrading would help. There is another issue maybe.

For the update, it's based on the scene change. Because there is no API to see if an output changes. I have to listen to scene changes and update all the devices of the concerned room...

Since the issue seems resolved I will close the issue. Please open a new one if you find something else.
