### ISSUE TITLE
Is it possible to add BL-KM300?

### ISSUE THREAD

**Issue by djacid** [gaetancollaud/digitalstrom-mqtt#19]
Hello, Could you please tell me if BL-KM300 is compatible with your code?

**Comment by gaetancollaud** [comment]
Hello,

I don't personally own this device. So I was never able to properly test it.

Have a look at #7. Unfortunately, there is currently an issue with the `heatingPower`. DigitalStrom is working on a new API, but it's not documented yet. I'm still waiting on this to see if it helps.

If the API doesn't come soon, I guess I will try to implement the workaround describe in [this comment](https://github.com/gaetancollaud/digitalstrom-mqtt/issues/7#issuecomment-817288342).

I will close this issue, feel free to put a :+1: or comment on#7.
