### ISSUE TITLE
Support for GE-UMV200

### ISSUE THREAD

**Issue by tchatziliadis** [gaetancollaud/digitalstrom-mqtt#22]
Hello, is it possible to add GE-UMV200? I recently purchased this device and unfortunately it's not working. Thank you in advance

**Comment by gaetancollaud** [comment]
Hello,

I'm sorry but I don't own this device. I cannot test myself.

What is not working? The device doesn't appear in MQTT?

Do you have any logs that could help?

Cheers

**Comment by tchatziliadis** [comment]
Sorry, my fault. It seems that is working as it should be. I forgot to fire a physical switch to update the scenes. I think you could add this device as supported ;) If there is any issue, I will create a new topic. Thank you very much
