### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by rvdgaag** [gaetancollaud/digitalstrom-mqtt#39]
Hi I managed to setup a mqtt server and have this nice link to send the digitalstrom device to Home Assistant.

But I can't manage to start the programm on my raspberry with Raspian everytime the raspberry reboots.

Any suggestion what to set in rc.local ?

Thanks

**Comment by rvdgaag** [comment]
found it with systemd

**Comment by gaetancollaud** [comment]
Glad you found a solution.
