### ISSUE TITLE
Openhab configuration example

### ISSUE THREAD

**Issue by gaetancollaud** [gaetancollaud/digitalstrom-mqtt#4]

**Comment by dylancollaud** [comment]
Example for a dimmer and a switch

**In the Thing**

Type dimmer	: LightCuisineLavaboMQTT [ commandTopic="digitalstrom/devices/Cuisine lavabo/brightness/command", stateTopic="digitalstrom/devices/Cuisine lavabo/brightness/state", min=0, max=100 ]
	
Type switch	: LightCuisineTableMQTT [ stateTopic="digitalstrom/devices/Salle a manger/brightness/state", commandTopic="digitalstrom/devices/Salle a manger/brightness/command", on="100.00", off="0.00" ]

**in the Item**

Dimmer LightCuisineLavabo "Cuisine lavabo" <light> { channel="mqtt:topic:myMQTTBroker:DigitalstromMQTT:LightCuisineLavaboMQTT", autoupdate="false" }

Switch LightCuisineTable "Table à manger" <light> { channel="mqtt:topic:myMQTTBroker:DigitalstromMQTT:LightCuisineTableMQTT", autoupdate="false" }
