### ISSUE TITLE
Devices recognized, but value not updating

### ISSUE THREAD

**Issue by sanchosk** [gaetancollaud/digitalstrom-mqtt#50]
I have to admit I am a complete noob in digitalSTROM ecosystem.
My friend has a new house with the system in it.
It was configured by the electrician from the company that sold him the house and the system more-or-less works (there are some quirks like lights turning off after few seconds, etc.).
I tried to use this integration and it works OK, but...
Some integrations are imported as lights - I can turn them on, off and they copy the real life of the device.
Other imported lights show as "Licht Gruppe H" for example and I can send command to turn them on or off from HA UI, but I don't see their value. There is a binary sensor for the same light group, but it's always off, even when the lights are on.
On top, the integration created a lot of energy/power/current instances that are all having value "unknown" - not that it's a problem, just curious if there is something I can set in dsS that will make the values show up...
Thanks again for the integration - this will make the house much more usable!

**Comment by gaetancollaud** [comment]
Hello,

I'm not exactly sure what you're talking about. I personally never used groups. And the goal of this integration is to have a direct access to single device. The goal is that you can then use home assistant or whatever home automation system to control your devices (and group them there if you need to).

**Comment by sanchosk** [comment]
The issue here is I was not the one setting up the ds system in the house and I am not qualified enough to ungroup/regroup the devices.
But I'll try to check if there is some more information I can gain from the system, but I need to get on-site :)

Thanks anyhow for great integration, it seems to work quite well for single lamps!

**Comment by gaetancollaud** [comment]
Thank you ;)
