### ISSUE TITLE
Stop Function

### ISSUE THREAD

**Issue by Sapp00** [gaetancollaud/digitalstrom-mqtt#9]
Hi,

I like your MQTT approach for DSS and it works quite good besides some minor issues.

Could you implement a stop command (for roller shutters)? Thats the only feature I am missing!

**Comment by gaetancollaud** [comment]
Hello,

Can you describe the minor issues?

I'm not against having a `stop` command, but then I would need an `up` and `down` as well.

I will see what I can do because right now I just use the `setOuputValue` of digitalSTROM, which is absolute. I never used the relative functions.

**Comment by Sapp00** [comment]
I just checked out the API. I think its good to implement by using zones (e.g., get the zoneID of the device, then /zone/callAction?application=2&id=X&action=app.stop). 
Maybe then command=UP->app.moveUp, command=DOWN->app.moveDown. Then it is still general supporting numeric values, but also is a workaround for the inaccurate behaviour of the digitalstrom system.
Then we could use the zones for moving up & down and the device for the angle of the blinds.

**Comment by gaetancollaud** [comment]
I really wanted to avoid working with scenes and zones. My goal was to target devices directly.

But it seems that there is no other way for the `stop` command. So maybe it's ok just for this one as it will not impact the others if they are not moving.

for `up` and `down` command I can always convert them to `100` and `0`.

**Comment by gaetancollaud** [comment]
@Sapp00 I implemented the `stop` command. Can you try this: https://github.com/gaetancollaud/digitalstrom-mqtt/releases/tag/1.3.2

**Comment by Sapp00** [comment]
Works like a charm, thank you.
